apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mlops-edge-central

resources:
  - openshift-ai/
  - flightctl/

commonLabels:
  app.kubernetes.io/part-of: mlops-edge
  app.kubernetes.io/component: central-cluster
  scenario: scenario-02-device-edge

